import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

export interface DetectedBuild {
  /** Dockerfile path relative to the build context. */
  dockerfile: string
  /** How we arrived at it, for the build log. */
  reason: string
  generated: boolean
}

interface PackageJson {
  scripts?: Record<string, string>
  dependencies?: Record<string, string>
  devDependencies?: Record<string, string>
  engines?: { node?: string }
}

const GENERATED_DIR = '.sitedeployer'

function readJson<T>(path: string): T | null {
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as T
  } catch {
    return null
  }
}

function nodeTag(pkg: PackageJson, contextDir: string): string {
  const nvmrc = join(contextDir, '.nvmrc')
  if (existsSync(nvmrc)) {
    const major = readFileSync(nvmrc, 'utf8').trim().replace(/^v/, '').split('.')[0]
    if (major && /^\d+$/.test(major)) return `${major}-alpine`
  }
  const engine = pkg.engines?.node
  const major = engine?.match(/(\d+)/)?.[1]
  return major ? `${major}-alpine` : '22-alpine'
}

function packageManager(contextDir: string): { install: string; runner: string } {
  if (existsSync(join(contextDir, 'pnpm-lock.yaml')))
    return { install: 'corepack enable && pnpm install --frozen-lockfile', runner: 'pnpm' }
  if (existsSync(join(contextDir, 'yarn.lock')))
    return { install: 'corepack enable && yarn install --immutable', runner: 'yarn' }
  if (existsSync(join(contextDir, 'package-lock.json'))) return { install: 'npm ci', runner: 'npm' }
  return { install: 'npm install --no-audit --no-fund', runner: 'npm' }
}

/** Where a framework drops its production build, when the app has no server of its own. */
function staticOutputDir(pkg: PackageJson): string {
  const deps = { ...pkg.dependencies, ...pkg.devDependencies }
  if (deps['react-scripts']) return 'build'
  if (deps['@angular/cli']) return 'dist'
  if (deps['vite'] || deps['astro'] || deps['svelte']) return 'dist'
  return 'dist'
}

function writeGenerated(contextDir: string, files: Record<string, string>): void {
  mkdirSync(join(contextDir, GENERATED_DIR), { recursive: true })
  for (const [name, body] of Object.entries(files)) {
    writeFileSync(join(contextDir, GENERATED_DIR, name), body, 'utf8')
  }
}

function nginxConf(port: number): string {
  return `server {
    listen ${port};
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    access_log /dev/stdout;
    error_log  /dev/stderr warn;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
`
}

/**
 * Picks the Dockerfile for a source tree, generating one when the project does
 * not ship its own. Generated files land in `<context>/.sitedeployer/` so the
 * source tree is never modified in place.
 */
export function detectBuild(contextDir: string, opts: { dockerfilePath?: string | null; containerPort: number }): DetectedBuild {
  if (opts.dockerfilePath) {
    const abs = join(contextDir, opts.dockerfilePath)
    if (!existsSync(abs)) throw new Error(`Configured dockerfilePath not found: ${opts.dockerfilePath}`)
    return { dockerfile: opts.dockerfilePath, reason: 'configured on the site', generated: false }
  }

  if (existsSync(join(contextDir, 'Dockerfile'))) {
    return { dockerfile: 'Dockerfile', reason: 'repository ships a Dockerfile', generated: false }
  }

  const pkg = readJson<PackageJson>(join(contextDir, 'package.json'))
  if (pkg) {
    const tag = nodeTag(pkg, contextDir)
    const pm = packageManager(contextDir)
    const hasStart = Boolean(pkg.scripts?.start)
    const hasBuild = Boolean(pkg.scripts?.build)

    if (hasStart) {
      const buildStep = hasBuild ? `RUN ${pm.runner} run build\n` : ''
      writeGenerated(contextDir, {
        Dockerfile: `# generated by site-deployer
FROM node:${tag}
WORKDIR /app
ENV NODE_ENV=production
COPY . .
RUN ${pm.install}
${buildStep}EXPOSE ${opts.containerPort}
CMD ["${pm.runner}", "start"]
`,
      })
      return {
        dockerfile: `${GENERATED_DIR}/Dockerfile`,
        reason: `generated: node ${tag} app with a "start" script`,
        generated: true,
      }
    }

    if (hasBuild) {
      const outDir = staticOutputDir(pkg)
      writeGenerated(contextDir, {
        Dockerfile: `# generated by site-deployer
FROM node:${tag} AS build
WORKDIR /app
COPY . .
RUN ${pm.install}
RUN ${pm.runner} run build

FROM nginx:alpine
COPY --from=build /app/${outDir} /usr/share/nginx/html
COPY ${GENERATED_DIR}/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE ${opts.containerPort}
`,
        'nginx.conf': nginxConf(opts.containerPort),
      })
      return {
        dockerfile: `${GENERATED_DIR}/Dockerfile`,
        reason: `generated: static build served by nginx from ./${outDir}`,
        generated: true,
      }
    }
  }

  if (existsSync(join(contextDir, 'index.html'))) {
    writeGenerated(contextDir, {
      Dockerfile: `# generated by site-deployer
FROM nginx:alpine
COPY . /usr/share/nginx/html
COPY ${GENERATED_DIR}/nginx.conf /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/${GENERATED_DIR} /usr/share/nginx/html/.git
EXPOSE ${opts.containerPort}
`,
      'nginx.conf': nginxConf(opts.containerPort),
    })
    return {
      dockerfile: `${GENERATED_DIR}/Dockerfile`,
      reason: 'generated: plain static site served by nginx',
      generated: true,
    }
  }

  throw new Error(
    'Could not determine how to build this project: no Dockerfile, no package.json with a start/build script, and no index.html. Add a Dockerfile or set dockerfilePath.',
  )
}

export { GENERATED_DIR }
